### ISSUE TITLE
Does not work with zookeeper 3.5 

### ISSUE THREAD

**Issue by netman2k** [itsaur/zookeeper-docker-swarm#1]
Hi,

Recently I have been working with your container image but I did not work correctly.
When I changed the version of the zookeeper to 3.4.12 and run it, It works very well.

My stack yaml configuration is pretty simple.
as you can see I used rebuilt container image, daehyung/zookeeper-ensemble-swarm:3.4.12.
The Dockerfile is the same except the version of the zookeeper.

```
version: '3.3'

services:
  # https://github.com/itsaur/zookeeper-docker-swarm
  # https://store.docker.com/community/images/itsaur/zookeeper-replicated/tags
  zookeeper:
    image: daehyung/zookeeper-ensemble-swarm:3.4.12
    ports:
      - 2181:2181
    environment:
      SERVICE_NAME: ${ZOOKEEPER_SERVICE_NAME:-zookeeper}
    networks:
      - zookeeper
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 30s
      placement:
       constraints:
         - node.role == manager
      resources:
        reservations:
          cpus: '0.02'
          memory: '1G'
        limits:
          cpus: '0.03'
          memory: '2G'
networks:
  zookeeper:
    external:
      name: ${ZOOKEEPER_NETWORK_NAME:-zookeeper}
``` 

Is there anything I did wrong or missed?
